export const CHANGE_TAB = "CHANGE_TAB";
export const SET_OVERVIEW_DATA = "SET_OVERVIEW_DATA";
export const SET_SHIPRAW_DATA = "SET_SHIPRAW_DATA";
export const SET_SPECIFICATION_DATA = "SET_SPECIFICATION_DATA";
export const SET_ITINERARIES_DATA = "SET_ITINERARIES_DATA";
export const SET_CABINS_DATA = "SET_CABIN_DATA";